### ISSUE TITLE
Record of static analysis

### ISSUE THREAD

**Issue by anderssonvivi** [ChristoferVikstroem/FaTS#23]
## Static Analysis
2023-12-14 using slither.
`pip3 install slither-analyzer`
`slither .`

- [x] Contract locking ether found:
        Contract Company (contracts/Company.sol#12-154) has payable functions:
         - Company.constructor(address,string,string) (contracts/Company.sol#50-58)
        But does not have a function to withdraw the ether

- [x] Contract locking ether found:´
        Contract CompanyFactory (contracts/CompanyFactory.sol#7-185) has payable functions:
         - CompanyFactory.constructor() (contracts/CompanyFactory.sol#41-43)
        But does not have a function to withdraw the ether

- [x] Company.constructor(address,string,string)._companyKey (contracts/Company.sol#51) lacks a zero-check on :
                - companyKey = _companyKey (contracts/Company.sol#55)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#missing-zero-address-validation

- [x] CompanyFactory.getAverageSalaryInSector(string) (contracts/CompanyFactory.sol#165-184) has external calls inside a loop: totalSalaries += company.getAverageSalary() * company.totalEmployees() (contracts/CompanyFactory.sol#173-175)

- [x] CompanyFactory.getAverageSalaryInSector(string) (contracts/CompanyFactory.sol#165-184) has external calls inside a loop: totalEmployees += company.totalEmployees() (contracts/CompanyFactory.sol#176)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation/#calls-inside-a-loop

- [x] Pragma version>=0.5.0<0.9.0 (contracts/Company.sol#2) is too complex

- [x] Pragma version>=0.5.0<0.9.0 (contracts/CompanyFactory.sol#2) is too complex
solc-0.8.19 is not recommended for deployment
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity

- [ ] Parameter Company.addEmployee(address,string,uint256)._title (contracts/Company.sol#64) is not in mixedCase
- [ ] Parameter Company.addEmployee(address,string,uint256)._salary (contracts/Company.sol#65) is not in mixedCase
- [ ] Parameter CompanyFactory.grantRegistryRight(address,string,string)._companyName (contracts/CompanyFactory.sol#49) is not in mixedCase
- [ ] Parameter CompanyFactory.grantRegistryRight(address,string,string)._sector (contracts/CompanyFactory.sol#50) is not in mixedCase
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#conformance-to-solidity-naming-conventions

- [x] Company.companyKey (contracts/Company.sol#14) should be immutable 
- [x] CompanyFactory.owner (contracts/CompanyFactory.sol#9) should be immutable 
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#state-variables-that-could-be-declared-immutable

INFO:Slither:. analyzed (2 contracts with 93 detectors), 14 result(s) found
